# Auto-generated by Migration Automation Platform.
# Source environment: on-prem-datacenter-1
# Target cloud: aws
# DO NOT hand-edit generated resource blocks -- edit the plan/inventory
# and regenerate instead, or changes will be lost on the next run.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}


resource "aws_vpc" "net_core" {
  cidr_block = "10.0.0.0/16"

  tags = {
    Name     = "core-network"
    SourceId = "net-core"
  }
}
