"""
IaC generation stage.

Turns a MigrationPlan (+ source Inventory for attribute detail) into
Terraform HCL for the target cloud. Every generated resource carries a
tag back to the source resource id so the mapping is traceable in both
directions -- essential for validation and rollback later.

Only AWS is implemented in depth (the demo target); the generator is
structured so a second `_aws_block_for_*` -> `_azure_block_for_*` set
of functions is the natural extension point for multi-cloud targets.
"""
from __future__ import annotations

import os

from .models import Inventory, MigrationPlan, Resource, ResourceType

HCL_HEADER = """\
# Auto-generated by Migration Automation Platform.
# Source environment: {source_env}
# Target cloud: {target_cloud}
# DO NOT hand-edit generated resource blocks -- edit the plan/inventory
# and regenerate instead, or changes will be lost on the next run.

terraform {{
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = var.aws_region
}}
"""

VARIABLES_TF = """\
variable "aws_region" {
  type    = string
  default = "us-east-1"
}
"""


def _tf_name(resource_id: str) -> str:
    return resource_id.replace("-", "_")


def _block_compute(r: Resource) -> str:
    name = _tf_name(r.id)
    instance_type = "t3.large" if r.attributes.get("ram_gb", 0) > 8 else "t3.medium"
    return f"""
resource "aws_instance" "{name}" {{
  ami           = var.ami_id
  instance_type = "{instance_type}"

  tags = {{
    Name           = "{r.name}"
    SourceId       = "{r.id}"
    MigrationWave  = "wave-placeholder"
  }}
}}
"""


def _block_database(r: Resource) -> str:
    name = _tf_name(r.id)
    engine = r.attributes.get("engine", "postgres")
    engine_map = {"postgresql": "postgres", "oracle": "oracle-se2"}
    tf_engine = engine_map.get(engine, engine)
    size_gb = r.attributes.get("size_gb", 100)
    return f"""
resource "aws_db_instance" "{name}" {{
  identifier        = "{r.id}"
  engine            = "{tf_engine}"
  allocated_storage = {size_gb}
  instance_class    = "db.t3.large"
  multi_az          = {str(bool(r.attributes.get("ha", False))).lower()}
  skip_final_snapshot = false
  final_snapshot_identifier = "{r.id}-final-snapshot"

  tags = {{
    Name     = "{r.name}"
    SourceId = "{r.id}"
  }}
}}
"""


def _block_object_storage(r: Resource) -> str:
    name = _tf_name(r.id)
    return f"""
resource "aws_s3_bucket" "{name}" {{
  bucket = "{r.id}-migrated"

  tags = {{
    Name     = "{r.name}"
    SourceId = "{r.id}"
  }}
}}
"""


def _block_network(r: Resource) -> str:
    name = _tf_name(r.id)
    cidr = r.attributes.get("cidr", "10.0.0.0/16")
    return f"""
resource "aws_vpc" "{name}" {{
  cidr_block = "{cidr}"

  tags = {{
    Name     = "{r.name}"
    SourceId = "{r.id}"
  }}
}}
"""


def _block_load_balancer(r: Resource) -> str:
    name = _tf_name(r.id)
    return f"""
resource "aws_lb" "{name}" {{
  name               = "{r.id}"
  internal           = false
  load_balancer_type = "application"

  tags = {{
    Name     = "{r.name}"
    SourceId = "{r.id}"
  }}
}}
"""


def _block_function(r: Resource) -> str:
    name = _tf_name(r.id)
    runtime = r.attributes.get("runtime", "python3.11")
    return f"""
resource "aws_lambda_function" "{name}" {{
  function_name = "{r.id}"
  runtime       = "{runtime}"
  handler       = "handler.main"
  filename      = "PLACEHOLDER_upload_deployment_package.zip"
  role          = var.lambda_exec_role_arn

  tags = {{
    Name     = "{r.name}"
    SourceId = "{r.id}"
  }}
}}
"""


def _block_dns(r: Resource) -> str:
    name = _tf_name(r.id)
    zone = r.attributes.get("zone", "example.internal")
    return f"""
resource "aws_route53_zone" "{name}" {{
  name = "{zone}"

  tags = {{
    Name     = "{r.name}"
    SourceId = "{r.id}"
  }}
}}
"""


_BLOCK_BUILDERS = {
    ResourceType.COMPUTE: _block_compute,
    ResourceType.DATABASE: _block_database,
    ResourceType.OBJECT_STORAGE: _block_object_storage,
    ResourceType.NETWORK: _block_network,
    ResourceType.LOAD_BALANCER: _block_load_balancer,
    ResourceType.FUNCTION: _block_function,
    ResourceType.DNS: _block_dns,
}


def generate_terraform(inventory: Inventory, plan: MigrationPlan, out_dir: str) -> list[str]:
    """Writes main.tf, variables.tf per wave into out_dir. Returns the
    list of file paths written."""
    os.makedirs(out_dir, exist_ok=True)
    written = []

    var_path = os.path.join(out_dir, "variables.tf")
    with open(var_path, "w") as f:
        f.write(VARIABLES_TF)
        f.write('\nvariable "ami_id" {\n  type = string\n}\n')
        f.write('\nvariable "lambda_exec_role_arn" {\n  type = string\n}\n')
    written.append(var_path)

    for wave_idx, wave in enumerate(plan.waves, start=1):
        wave_path = os.path.join(out_dir, f"wave_{wave_idx:02d}.tf")
        blocks = [
            HCL_HEADER.format(
                source_env=inventory.source_environment,
                target_cloud=plan.target_cloud,
            )
            if wave_idx == 1
            else f"# Wave {wave_idx}\n"
        ]
        for rid in wave:
            r = inventory.by_id(rid)
            builder = _BLOCK_BUILDERS.get(r.type)
            if builder:
                block = builder(r).replace("wave-placeholder", str(wave_idx))
                blocks.append(block)
            else:
                blocks.append(f"\n# NOTE: no Terraform mapping yet for resource "
                               f"'{r.id}' (type={r.type.value}); requires manual handling.\n")
        with open(wave_path, "w") as f:
            f.write("\n".join(blocks))
        written.append(wave_path)

    return written
